name: Django Migration Checker
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/toannvbk93
        with:
          fetch-depth: 1

      - name: Django Migration Checker
        uses: hardcoretech/django-migration-checker-action@v1
        with:
          app-path: blog